// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CIDRPolicy CIDR endpoint policy
// swagger:model CIDRPolicy

type CIDRPolicy struct {

	// List of CIDR egress rules
	Egress []string `json:"egress"`

	// Names of L3 policies in effect on this endpoint
	EgressSourceUserPolicy []string `json:"egress-source-user-policy"`

	// List of CIDR ingress rules
	Ingress []string `json:"ingress"`

	// Names of L3 policies in effect on this endpoint
	IngressSourceUserPolicy []string `json:"ingress-source-user-policy"`
}

/* polymorph CIDRPolicy egress false */

/* polymorph CIDRPolicy egress-source-user-policy false */

/* polymorph CIDRPolicy ingress false */

/* polymorph CIDRPolicy ingress-source-user-policy false */

// Validate validates this c ID r policy
func (m *CIDRPolicy) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEgress(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateEgressSourceUserPolicy(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateIngress(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateIngressSourceUserPolicy(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CIDRPolicy) validateEgress(formats strfmt.Registry) error {

	if swag.IsZero(m.Egress) { // not required
		return nil
	}

	return nil
}

func (m *CIDRPolicy) validateEgressSourceUserPolicy(formats strfmt.Registry) error {

	if swag.IsZero(m.EgressSourceUserPolicy) { // not required
		return nil
	}

	return nil
}

func (m *CIDRPolicy) validateIngress(formats strfmt.Registry) error {

	if swag.IsZero(m.Ingress) { // not required
		return nil
	}

	return nil
}

func (m *CIDRPolicy) validateIngressSourceUserPolicy(formats strfmt.Registry) error {

	if swag.IsZero(m.IngressSourceUserPolicy) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CIDRPolicy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CIDRPolicy) UnmarshalBinary(b []byte) error {
	var res CIDRPolicy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
