// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DNSLookup An IP -> DNS mapping, with metadata
// swagger:model DNSLookup

type DNSLookup struct {

	// An IP
	Address string `json:"address,omitempty"`

	// DNS name
	Fqdn string `json:"fqdn,omitempty"`

	// The endpoint that made this lookup, or 0 for the agent itself.
	LookupSource int64 `json:"lookup-source,omitempty"`

	// The absolute time when this data was recieved
	LookupTime strfmt.DateTime `json:"lookup-time,omitempty"`

	// The TTL in the DNS response
	TTL int64 `json:"ttl,omitempty"`
}

/* polymorph DNSLookup address false */

/* polymorph DNSLookup fqdn false */

/* polymorph DNSLookup lookup-source false */

/* polymorph DNSLookup lookup-time false */

/* polymorph DNSLookup ttl false */

// Validate validates this DNS lookup
func (m *DNSLookup) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DNSLookup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DNSLookup) UnmarshalBinary(b []byte) error {
	var res DNSLookup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
