// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// L4Policy L4 endpoint policy
// swagger:model L4Policy

type L4Policy struct {

	// List of L4 egress rules
	Egress []string `json:"egress"`

	// Names of L4 policies in effect on this endpoint
	EgressSourceUserPolicy []string `json:"egress-source-user-policy"`

	// List of L4 ingress rules
	Ingress []string `json:"ingress"`

	// Names of L4 policies in effect on this endpoint
	IngressSourceUserPolicy []string `json:"ingress-source-user-policy"`
}

/* polymorph L4Policy egress false */

/* polymorph L4Policy egress-source-user-policy false */

/* polymorph L4Policy ingress false */

/* polymorph L4Policy ingress-source-user-policy false */

// Validate validates this l4 policy
func (m *L4Policy) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEgress(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateEgressSourceUserPolicy(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateIngress(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateIngressSourceUserPolicy(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *L4Policy) validateEgress(formats strfmt.Registry) error {

	if swag.IsZero(m.Egress) { // not required
		return nil
	}

	return nil
}

func (m *L4Policy) validateEgressSourceUserPolicy(formats strfmt.Registry) error {

	if swag.IsZero(m.EgressSourceUserPolicy) { // not required
		return nil
	}

	return nil
}

func (m *L4Policy) validateIngress(formats strfmt.Registry) error {

	if swag.IsZero(m.Ingress) { // not required
		return nil
	}

	return nil
}

func (m *L4Policy) validateIngressSourceUserPolicy(formats strfmt.Registry) error {

	if swag.IsZero(m.IngressSourceUserPolicy) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *L4Policy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *L4Policy) UnmarshalBinary(b []byte) error {
	var res L4Policy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
